name: Node.js CD

on:
    push:
        branches:
            - next

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - run: npm ci

            - run: npm run build-github

            #Safety against pushing broken code
            - name: Run ESLint
              uses: stefanoeb/eslint-action@1.0.2
              with:
                  files: ./src

            - name: Deploy
              uses: crazy-max/ghaction-github-pages@v2
              with:
                  keep_history: true
                  build_dir: deploy
                  jekyll: false
                  target_branch: live
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
